# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170215_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_author', models.CharField(max_length=24)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Post')),
            ],
        ),
    ]
